name: el_paso_events
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.5.0
  scoped_model: ^2.0.0
  path_provider: ^2.1.5 
  intl: ^0.18.1
  http: ^1.3.0
  cloud_firestore: ^5.6.6
  firebase_core: ^3.13.0
  url_launcher: ^6.3.1
  firebase_auth: ^5.5.3
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/El_Paso_Star_at_Sunset.png"

flutter:
  uses-material-design: true

  assets:
    - assets/El_Paso_Star_at_Sunset.png
    - assets/default_avatar.png
    # - assets/your_other_image.png (add more as needed)
    # - assets/ (to include entire directory)

  # To enable custom fonts, uncomment and customize this section:
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: fonts/Montserrat-Regular.ttf
  #       - asset: fonts/Montserrat-Bold.ttf
  #         weight: 700
